[workspace]
members = ["axum-extract", "core", "stores"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Jimmie Lovell <jimmieomlovell@gmail.com>"]
license = "MIT"
homepage = "https://github.com/jimmielovell/ruse"
keywords = ["axum", "session", "sessions", "cookie", "tower"]
categories = ["asynchronous", "network-programming", "web-programming"]
repository = "https://github.com/jimmielovell/ruse"
readme = "README.md"

[package]
name = "ruse"
description = "🥠 Sessions as a `tower` and `axum` middleware."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true

[dependencies]
async-trait = "0.1.77"
axum = { version = "0.7.3", features = ["http2", "macros"] }
axum-core = "0.4.3"
blake3 = { version = "1.5.0", features = ["rayon"] }
cookie = "0.18.0"
dashmap = { version = "5.5.3", features = ["serde"] }
http = "1.0.0"
parking_lot = "0.12.1"
pin-project-lite = "0.2.13"
rand = "0.8.5"
serde = "1.0.195"
tokio = { version = "1.35.1", features = ["full"] }
tower = "0.4.13"
tower-cookies = "0.10.0"
tracing = "0.1.40"
