[package]
name = "ruse"
description = "Sessions as a tower middleware"
version = "0.1.4"
edition = "2021"
authors = ["Jimmie Lovell <jimmieomlovell@gmail.com>"]
license = "MIT"
homepage = "https://github.com/jimmielovell/ruse"
keywords = ["axum", "session", "sessions", "cookie"]
categories = ["asynchronous", "network-programming", "web-programming"]
repository = "https://github.com/jimmielovell/ruse"

[dependencies]
async-trait = "0.1.78"
axum-core = "0.4.3"
base64 = "0.22.0"
cookie = "0.18.0"
fred = "8.0.5"
http = "1.0.0"
parking_lot = { version = "0.12.1", features = ["serde"] }
pin-project-lite = "0.2.13"
rand = "0.8.5"
rmp-serde = "1.1.2"
serde = { version = "1.0.197", features = ["derive"] }
thiserror = "1.0.58"
tokio = { version = "1.36.0", features = ["full"] }
tower = "0.4.13"
tower-cookies = "0.10.0"
tracing = { version = "0.1.40", features = ["log"] }

[dev-dependencies]
axum = "0.7.4"
http-body-util = "0.1.1"
