[package]
name = "ruse"
description = "Sessions as a `tower` and `axum` middleware."
version = "0.1.0"
edition = "2021"
authors = ["Jimmie Lovell <jimmieomlovell@gmail.com>"]
license = "MIT"
homepage = "https://github.com/jimmielovell/ruse"
keywords = ["axum", "session", "sessions", "cookie", "tower"]
categories = ["asynchronous", "network-programming", "web-programming"]
repository = "https://github.com/jimmielovell/ruse"
readme = "README.md"

[dependencies]
async-trait = "0.1.77"
cookie = "0.18.0"
http = "1.0.0"
parking_lot = { version = "0.12.1", features = ["serde"] }
thiserror = "1.0.58"
tokio = { version = "1.35.1", features = ["full"] }
axum-core = "0.4.3"
pin-project-lite = "0.2.13"
rand = "0.8.5"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.114"
tower = "0.4.13"
tower-cookies = "0.10.0"
tracing = { version = "0.1.40", features = ["log"] }
fred = "8.0.5"
axum = "0.7.4"
rmp-serde = "1.1.2"
base64 = "0.22.0"
