[workspace]
members = [".", "ruse-core", "stores"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Jimmie Lovell <jimmieomlovell@gmail.com>"]
license = "MIT"
homepage = "https://github.com/jimmielovell/ruse"
keywords = ["axum", "session", "sessions", "cookie", "tower"]
categories = ["asynchronous", "network-programming", "web-programming"]
repository = "https://github.com/jimmielovell/ruse"
readme = "README.md"

[package]
name = "ruse"
description = "🥠 Sessions as a `tower` and `axum` middleware."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true
readme.workspace = true

[workspace.dependencies]
ruse = { version = "=0.1.0", path = "." }
ruse_core = { version = "=0.1.0", path = "ruse-core" }
stores = { version = "=0.1.0", path = "stores" }

async-trait = "0.1.77"
cookie = "0.18.0"
dashmap = { version = "5.5.3", features = ["serde"] }
http = "1.0.0"
parking_lot = { version = "0.12.1", features = ["serde"] }
serde = "1.0.195"
tokio = { version = "1.35.1", features = ["full"] }

[dependencies]
cookie = "0.18.0"
ruse_core = { workspace = true }
stores = { workspace = true }
tracing = { version = "0.1.40", features = ["log"] }

axum = "0.7.4"
tokio.workspace = true
tower-cookies = "0.10.0"

[dev-dependencies]
axum = "0.7.4"
tokio.workspace = true
tower-cookies = "0.10.0"
