[package]
name = "stores"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait.workspace = true
dashmap.workspace = true
fred = "8.0.1"
ruse_core.workspace = true
tokio.workspace = true
